"""initial postgresql schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-28 15:42:55.870081+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('access_link', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_access_link'), 'users', ['access_link'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('credit_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_codes_code'), 'credit_codes', ['code'], unique=True)
    op.create_table('custom_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_prompts_id'), 'custom_prompts', ['id'], unique=False)
    op.create_table('paper_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_projects_created_at'), 'paper_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_projects_id'), 'paper_projects', ['id'], unique=False)
    op.create_index(op.f('ix_paper_projects_is_archived'), 'paper_projects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_paper_projects_user_id'), 'paper_projects', ['user_id'], unique=False)
    op.create_table('queue_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_status_id'), 'queue_status', ['id'], unique=False)
    op.create_index(op.f('ix_queue_status_session_id'), 'queue_status', ['session_id'], unique=True)
    op.create_table('registration_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_invites_code'), 'registration_invites', ['code'], unique=True)
    op.create_index(op.f('ix_registration_invites_created_by_user_id'), 'registration_invites', ['created_by_user_id'], unique=False)
    op.create_index('idx_registration_invites_created_by_user_id', 'registration_invites', ['created_by_user_id'], unique=False)
    op.create_table('saved_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_specs_id'), 'saved_specs', ['id'], unique=False)
    op.create_index(op.f('ix_saved_specs_user_id'), 'saved_specs', ['user_id'], unique=False)
    op.create_table('user_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_last4', sa.String(length=8), nullable=False),
    sa.Column('polish_model', sa.String(length=100), nullable=False),
    sa.Column('enhance_model', sa.String(length=100), nullable=False),
    sa.Column('emotion_model', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_provider_configs_user_id'), 'user_provider_configs', ['user_id'], unique=True)
    op.create_table('optimization_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('total_segments', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_segment_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('polish_model', sa.String(length=100), nullable=True),
    sa.Column('polish_api_key', sa.String(length=255), nullable=True),
    sa.Column('polish_base_url', sa.String(length=255), nullable=True),
    sa.Column('enhance_model', sa.String(length=100), nullable=True),
    sa.Column('enhance_api_key', sa.String(length=255), nullable=True),
    sa.Column('enhance_base_url', sa.String(length=255), nullable=True),
    sa.Column('emotion_model', sa.String(length=100), nullable=True),
    sa.Column('emotion_api_key', sa.String(length=255), nullable=True),
    sa.Column('emotion_base_url', sa.String(length=255), nullable=True),
    sa.Column('processing_mode', sa.String(length=50), nullable=True),
    sa.Column('billing_mode', sa.String(length=20), nullable=True),
    sa.Column('credential_source', sa.String(length=20), nullable=True),
    sa.Column('charge_status', sa.String(length=20), nullable=True),
    sa.Column('charged_credits', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['paper_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_sessions_created_at'), 'optimization_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_optimization_sessions_id'), 'optimization_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_sessions_project_id'), 'optimization_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_optimization_sessions_session_id'), 'optimization_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_optimization_sessions_status'), 'optimization_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_optimization_sessions_user_id'), 'optimization_sessions', ['user_id'], unique=False)
    op.create_index('idx_opt_session_created_at', 'optimization_sessions', ['created_at'], unique=False)
    op.create_index('idx_opt_session_status', 'optimization_sessions', ['status'], unique=False)
    op.create_index('idx_opt_session_user_id', 'optimization_sessions', ['user_id'], unique=False)
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('segment_index', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('before_text', sa.Text(), nullable=True),
    sa.Column('after_text', sa.Text(), nullable=True),
    sa.Column('changes_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['optimization_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_id'), 'change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_change_logs_segment_index'), 'change_logs', ['segment_index'], unique=False)
    op.create_index(op.f('ix_change_logs_session_id'), 'change_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_change_logs_stage'), 'change_logs', ['stage'], unique=False)
    op.create_index('idx_change_log_segment_index', 'change_logs', ['segment_index'], unique=False)
    op.create_index('idx_change_log_session_id', 'change_logs', ['session_id'], unique=False)
    op.create_index('idx_change_log_stage', 'change_logs', ['stage'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('related_code_id', sa.Integer(), nullable=True),
    sa.Column('related_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_code_id'], ['credit_codes.id'], ),
    sa.ForeignKeyConstraint(['related_session_id'], ['optimization_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('optimization_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('segment_index', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('polished_text', sa.Text(), nullable=True),
    sa.Column('enhanced_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_title', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['optimization_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_segments_id'), 'optimization_segments', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_segments_segment_index'), 'optimization_segments', ['segment_index'], unique=False)
    op.create_index(op.f('ix_optimization_segments_session_id'), 'optimization_segments', ['session_id'], unique=False)
    op.create_index(op.f('ix_optimization_segments_status'), 'optimization_segments', ['status'], unique=False)
    op.create_index('idx_opt_segment_index', 'optimization_segments', ['segment_index'], unique=False)
    op.create_index('idx_opt_segment_session_id', 'optimization_segments', ['session_id'], unique=False)
    op.create_index('idx_opt_segment_status', 'optimization_segments', ['status'], unique=False)
    op.create_table('session_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('history_data', sa.Text(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['optimization_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_history_id'), 'session_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_history_id'), table_name='session_history')
    op.drop_table('session_history')
    op.drop_index('idx_opt_segment_status', table_name='optimization_segments')
    op.drop_index('idx_opt_segment_session_id', table_name='optimization_segments')
    op.drop_index('idx_opt_segment_index', table_name='optimization_segments')
    op.drop_index(op.f('ix_optimization_segments_status'), table_name='optimization_segments')
    op.drop_index(op.f('ix_optimization_segments_session_id'), table_name='optimization_segments')
    op.drop_index(op.f('ix_optimization_segments_segment_index'), table_name='optimization_segments')
    op.drop_index(op.f('ix_optimization_segments_id'), table_name='optimization_segments')
    op.drop_table('optimization_segments')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('idx_change_log_stage', table_name='change_logs')
    op.drop_index('idx_change_log_session_id', table_name='change_logs')
    op.drop_index('idx_change_log_segment_index', table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_stage'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_session_id'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_segment_index'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_id'), table_name='change_logs')
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_optimization_sessions_user_id'), table_name='optimization_sessions')
    op.drop_index(op.f('ix_optimization_sessions_status'), table_name='optimization_sessions')
    op.drop_index(op.f('ix_optimization_sessions_session_id'), table_name='optimization_sessions')
    op.drop_index(op.f('ix_optimization_sessions_project_id'), table_name='optimization_sessions')
    op.drop_index(op.f('ix_optimization_sessions_id'), table_name='optimization_sessions')
    op.drop_index(op.f('ix_optimization_sessions_created_at'), table_name='optimization_sessions')
    op.drop_index('idx_opt_session_user_id', table_name='optimization_sessions')
    op.drop_index('idx_opt_session_status', table_name='optimization_sessions')
    op.drop_index('idx_opt_session_created_at', table_name='optimization_sessions')
    op.drop_table('optimization_sessions')
    op.drop_index(op.f('ix_user_provider_configs_user_id'), table_name='user_provider_configs')
    op.drop_table('user_provider_configs')
    op.drop_index(op.f('ix_saved_specs_user_id'), table_name='saved_specs')
    op.drop_index(op.f('ix_saved_specs_id'), table_name='saved_specs')
    op.drop_table('saved_specs')
    op.drop_index(op.f('ix_registration_invites_created_by_user_id'), table_name='registration_invites')
    op.drop_index(op.f('ix_registration_invites_code'), table_name='registration_invites')
    op.drop_index('idx_registration_invites_created_by_user_id', table_name='registration_invites')
    op.drop_table('registration_invites')
    op.drop_index(op.f('ix_queue_status_session_id'), table_name='queue_status')
    op.drop_index(op.f('ix_queue_status_id'), table_name='queue_status')
    op.drop_table('queue_status')
    op.drop_index(op.f('ix_paper_projects_user_id'), table_name='paper_projects')
    op.drop_index(op.f('ix_paper_projects_is_archived'), table_name='paper_projects')
    op.drop_index(op.f('ix_paper_projects_id'), table_name='paper_projects')
    op.drop_index(op.f('ix_paper_projects_created_at'), table_name='paper_projects')
    op.drop_table('paper_projects')
    op.drop_index(op.f('ix_custom_prompts_id'), table_name='custom_prompts')
    op.drop_table('custom_prompts')
    op.drop_index(op.f('ix_credit_codes_code'), table_name='credit_codes')
    op.drop_table('credit_codes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_access_link'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
